name: GitKill
on: [push, pull_request]
jobs:
  build:
    name: RUN
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P]
    timeout-minutes: 240
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: Run_GO
      run: |
         sudo apt update
